/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#484848",
        "tertiary-container": "#fc4c00",
        "on-secondary-fixed-variant": "#5a5c5c",
        "on-background": "#e7e5e4",
        "primary": "#c6c6c7",
        "surface-bright": "#2c2c2c",
        "outline": "#767575",
        "primary-dim": "#b8b9b9",
        "tertiary": "#ff7346",
        "on-tertiary-container": "#0e0100",
        "background": "#0e0e0e",
        "surface-container-highest": "#252626",
        "on-surface-variant": "#acabaa",
        "on-primary": "#3f4041",
        "surface-variant": "#252626",
        "tertiary-fixed": "#fc4c00",
        "secondary-fixed-dim": "#d4d4d4",
        "on-tertiary": "#420d00",
        "secondary-fixed": "#e2e2e2",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-fixed": "#000000",
        "inverse-primary": "#5e5f60",
        "secondary-container": "#3a3c3c",
        "surface-dim": "#0e0e0e",
        "error-container": "#7f2927",
        "error": "#ee7d77",
        "surface-container": "#191a1a",
        "inverse-on-surface": "#565554",
        "surface-tint": "#c6c6c7",
        "error-dim": "#bb5551",
        "surface": "#0e0e0e",
        "on-error-container": "#ff9993",
        "primary-fixed": "#e2e2e2",
        "secondary": "#9d9e9e",
        "on-tertiary-fixed-variant": "#2e0700",
        "on-primary-fixed": "#3e4040",
        "on-primary-container": "#d0d0d0",
        "surface-container-lowest": "#000000",
        "surface-container-high": "#1f2020",
        "on-error": "#490106",
        "on-secondary-container": "#bfbfbf",
        "primary-fixed-dim": "#d4d4d4",
        "secondary-dim": "#9d9e9e",
        "on-primary-fixed-variant": "#5a5c5c",
        "on-surface": "#e7e5e4",
        "surface-container-low": "#131313",
        "on-secondary-fixed": "#3e4040",
        "tertiary-dim": "#ff7346",
        "primary-container": "#454747",
        "tertiary-fixed-dim": "#e64500",
        "on-secondary": "#1f2021"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
